name: Release Russia blocked domains lists

on:
  workflow_dispatch:

env:
  ANTIFILTER_URL: https://community.antifilter.download/list/domains.lst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout V2Ray/XRay domain list builder
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: geosite-builder

      - name: Checkout itdoginfo custom domain lists
        uses: actions/checkout@v4
        with:
          repository: itdoginfo/allow-domains
          path: itdoginfo-domains

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: geosite-builder/go.mod
          cache-dependency-path: geosite-builder/go.sum

      - name: Prepare working directories
        run: |
          mkdir src geosite-data release
          cp itdoginfo-domains/src/Russia-domains-inside.lst src/itdoginfo-inside.lst
          cp itdoginfo-domains/src/Russia-domains-outside.lst src/itdoginfo-outside.lst

      - name: Download antifilter community domains list
        run: curl --location "$ANTIFILTER_URL" --output 'src/antifilter-community.lst' --fail --no-progress-meter

      - name: Prepare V2Ray/XRay domain lists
        run: |
          cat src/antifilter-community.lst | tee -a  >/dev/null \
            geosite-data/antifilter-community geosite-data/all
          cat src/itdoginfo-inside.lst | tee -a >/dev/null \
            geosite-data/itdoginfo-inside geosite-data/all
          cat src/itdoginfo-outside.lst | tee -a >/dev/null \
            geosite-data/itdoginfo-outside geosite-data/all-outside

      - name: Build V2Ray/XRay geosite file
        working-directory: geosite-builder
        run: go run . -datapath '../geosite-data' --outputname 'ru-blocked.dat' --outputdir '../release'

      - name: Zip files
        run: |
          zip -9 --junk-paths release/ru-blocked.dat.zip release/ru-blocked.dat
          zip -9 --recurse-paths release/src.zip src/ geosite-data/

      - name: Calculate checksums
        working-directory: release
        run: for file in *; do sha256sum $file > $file.sha256sum; done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
