name: Release Russia blocked domains lists

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * *"

env:
  ANTIFILTER_URL: https://community.antifilter.download/list/domains.lst

jobs:
  build-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set variables when running on schedule
        run: |
          echo "RELEASE_NAME=Released on $(date '+%Y-%m-%d')" >> $GITHUB_ENV
          echo "TAG_NAME=$(date '+%Y%m%d')" >> $GITHUB_ENV
    
      - name: Checkout V2Ray/XRay domain list builder
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: geosite-builder

      - name: Checkout itdoginfo custom domain lists
        uses: actions/checkout@v4
        with:
          repository: itdoginfo/allow-domains
          path: itdoginfo-domains

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: geosite-builder/go.mod
          cache-dependency-path: geosite-builder/go.sum

      - name: Prepare working directories
        run: |
          mkdir src geosite-data release
          cp itdoginfo-domains/src/Russia-domains-inside.lst src/itdoginfo-inside.lst
          cp itdoginfo-domains/src/Russia-domains-outside.lst src/itdoginfo-outside.lst

      - name: Download antifilter community domains list
        run: curl --location "$ANTIFILTER_URL" --output 'src/antifilter-community.lst' --fail --no-progress-meter

      - name: Prepare V2Ray/XRay domain lists
        run: |
          cat src/antifilter-community.lst | tee -a  >/dev/null \
            geosite-data/antifilter-community geosite-data/all
          cat src/itdoginfo-inside.lst | tee -a >/dev/null \
            geosite-data/itdoginfo-inside geosite-data/all
          cat src/itdoginfo-outside.lst | tee -a >/dev/null \
            geosite-data/itdoginfo-outside geosite-data/all-outside

      - name: Build V2Ray/XRay geosite file
        working-directory: geosite-builder
        run: go run . -datapath '../geosite-data' --outputname 'ru-blocked.dat' --outputdir '../release'

      - name: Zip files
        run: |
          zip -9 --junk-paths release/ru-blocked.dat.zip release/ru-blocked.dat
          zip -9 --recurse-paths release/src-data.zip src/ geosite-data/

      - name: Calculate checksums
        working-directory: release
        run: for file in *; do sha256sum $file > $file.sha256sum; done

      - name: Download latest release hashes
        uses: robinraju/release-downloader@v1.9
        continue-on-error: true
        with:
          latest: true
          fileName: '*.sha256sum'
          out-file-path: release-latest
          
      - name: Check for changes
        id: check-for-changes
        run: |
          for file in release/*.dat.sha256sum; do
            if ! cmp $file release-latest/$(basename $file)    ; then
              echo "#### Changes found, releasing! :rocket:" >> $GITHUB_STEP_SUMMARY
              echo "HAS_CHANGES=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          done
          echo "#### No changes found, skipping release. :zzz:" >> $GITHUB_STEP_SUMMARY

      - name: Prepare release notes
        if: ${{ steps.check-for-changes.outputs.HAS_CHANGES }}
        run: |
          echo -n "Всего уникальных имён сайтов: " >> RELEASE_NOTES
          cat geosite-data/all | grep -v -e '^#' -e '^[[:space:]]*$' | sort | uniq | wc -l >> RELEASE_NOTES 
          
      - name: Release
        if: ${{ steps.check-for-changes.outputs.HAS_CHANGES }}
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ env.RELEASE_NAME }}
          tag_name: ${{ env.TAG_NAME }}
          body_path: RELEASE_NOTES
          files: release/*
