name: Release Russia blocked domains lists

on:
  workflow_dispatch:

env:
  ANTIFILTER_URL: https://community.antifilter.download/listdomains.lst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:          
      - name: Checkout V2Ray/XRay domain list builder
        uses: actions/checkout@v4
        with:
          repository: v2fly/domain-list-community
          path: geosite-builder

      - name: Checkout itdoginfo custom domain lists
        uses: actions/checkout@v4
        with:
          repository: itdoginfo/allow-domains
          path: itdoginfo-domains

      - name: Download antifilter community domains list
        run: curl --location "$ANTIFILTER_URL" --output 'antifilter.lst' --fail --no-progress-meter
          

      
